title: Modulblog BAIN
author: Lea Reinhold
email: lea.reinhold@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Bibliothek, Archiv, Informatik, Open Source
theme: minima

# social links
github_username:  leareinhold

show_excerpts: true # set to false to remove excerpts on the homepage
